version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7
    steps:
      - checkout

      - run:
          name: Run Composer
          command: composer install

      - run:
          name: Run Specs
          command: ./bin/phpspec run
